### ISSUE TITLE
Record Screen Audio & users audio through wired Headphone

### ISSUE THREAD

**Issue by pzeepzee** [thetabbycat/apps#1]
I just bought the app in the App Store, but wish I could record the screen audio while also speaking through the mic on my world headphone.
For some reason, it only records my voice and not the audio on the screen, just screen video only.
Is there a way I can record & playback my voice (through headphone's mic) + screen audio at the same time?
Will be really helpful for me during meetings
Thanks

**Comment by stevenselcuk** [comment]
Sorry for the late answer :/ I've already written on Twitter but as a future reference I'd like to copy it here.

Unfortunately, it's about Apple's limitations. You can record only with the active input device simultaneously. It's not impossible but App Store will reject the app immediately if I patch it. But wait, you can still bypass this by audio hijacking.

You can use Loopback (formerly SoundFlower). Check out our config. We are using it on a daily basis for recording Zoom, browser, mic, etc. while monitoring the mixed sound with headphones.

![ref1](https://i.imgur.com/jfuUQAn.png)
![ref2](https://i.imgur.com/BatYGgK.png)
